### ISSUE TITLE
Constant element from the finite field

### ISSUE THREAD

**Issue by ssahai** [arkworks-rs/snark#101]
To assign a random element from the field, we can do the following

`let x = Fr::rand(rng);`

How can we assign to `x` a constant element from the field? For example: `let x = Fr::42`, which assigns the field element `42` to `x`?

**Comment by 95DDB** [comment]
The easiest and most immediate way:

```
use std::str::FromStr;
let x = Fr::from_str("42").map_err(|_|()).unwrap();
```
With `Fr` being a `PrimeField`

**Comment by Pratyush** [comment]
A cleaner way is to just do `let x = Fr::from(42u64)`

**Comment by ssahai** [comment]
Thanks. This perfectly works!

**Comment by ssahai** [comment]
Thanks! This works perfectly.

**Comment by ssahai** [comment]
Thanks! This works perfectly while assigning to variables and using it in function calls.

But, I am facing issues when trying to use field constants while creating circuits. What is the best way to use field constants in `add_assign` or `mul_assign`?

**Comment by ssahai** [comment]
In the following snippet, we can create a circuit for the equation `x^2 + x + 1`.

```
let y_value = x_value.map (|mut e| {
            e.mul_assign(&x_value.unwrap());     // x^2
            e.add_assign(&x_value.unwrap());     // x^2 + x
            e.add_assign(&ConstraintF::one());   // x^2 + x + 1   
            e 
        });
```
where `x_value` is of type ` x_value: Option<F>`.

But how can we add additive or multiplicative constants?

For example, how to add constraints for `5x^2 + x + 1` or `x^2 + x + 5`?

**Comment by ssahai** [comment]
I figured out the problem here! The issue in using `Fr::from(42u64)` while generating circuits with additive and multiplicative constants was because the trait `ConstraintF` was bounded incorrectly! The trait should have been bounded as `<ConstraintF: PrimeField>`, whereas it was bounded as `<ConstraintF: Field>` in my code. Fixing the trait bound fixed the errors.

**Comment by Fiono11** [comment]
Does this also work for ```let x = E::Fr::from(42u64), where E: PairingEngine```? It gives me an error because it expects a "u8". How can I solve this?
