### ISSUE TITLE
Point with different representation

### ISSUE THREAD

**Issue by Fiono11** [arkworks-rs/snark#103]
Hello! I have the following snippet of code:

```rust 
use algebra::{PairingEngine, ProjectiveCurve, Group};

fn main() {
 let g = E::G1Projective::prime_subgroup_generator();
        let x = E::Fr::from(4);
        let q: E::G1Projective = g.mul(&x);
        assert_eq!(g+&(g+&(g+&g)), q);
        println!("q: {:#?}", q);
        println!("4g: {:#?}", g+&(g+&(g+&g)));
}
```
The assert passes, however the prints are different. Is it because one is of type ProjectiveCurve and the other Group? How can I convert one representation to/from another? Thanks!

**Comment by kobigurk** [comment]
Since these are projective coordinates, for points to be equal they don’t have to be exactly the same - they just have to be a scalar multiple apart.
If you convert them into affine coordinates, using `into_affine()`, you should be good!

**Comment by Fiono11** [comment]
> Since these are projective coordinates, for points to be equal they don’t have to be exactly the same - they just have to be a scalar multiple apart.

Can you explain me why is that, please?
