### ISSUE TITLE
Serialization performance degradation

### ISSUE THREAD

**Issue by gakonst** [arkworks-rs/snark#130]
It seems to me that the serialization introduced in #109 is slower than the one @kobigurk had implemented in https://github.com/scipr-lab/zexe/pull/73 (which I extended to support uncompressed mode in: https://github.com/scipr-lab/zexe/pull/99/)

Compressed is ~20% slower, uncompressed is ~40%

Benchmarks - comparison in https://github.com/gakonst/zexe-serialization-comparison.

As a sidenote, it'd be nice if we introduced these benchmarks to the repo, to ensure we profile i/o as well

cc @paberr

**Comment by paberr** [comment]
Interesting observation.
It seems a bit counterintuitive to me as #109 mainly changed the interface and actually reduced the number of copy operations.
I'll have to look into it a bit more closely.

**Comment by paberr** [comment]
After inlining some frequently used, small functions in my code, the performance is much closer.

Here's an excerpt from `cargo bench` on your benchmark:
```
Run 1:
write/ours              time:   [120.91 us 123.47 us 126.48 us]
write/theirs            time:   [115.68 us 116.79 us 117.96 us]

write_uncompressed/ours time:   [76.133 us 76.303 us 76.520 us]
write_uncompressed/theirs
                        time:   [98.548 us 98.756 us 99.010 us]

Run 2:
write/ours              time:   [108.89 us 109.19 us 109.51 us]
write/theirs            time:   [111.54 us 111.85 us 112.18 us]

write_uncompressed/ours time:   [76.254 us 76.541 us 76.901 us]
write_uncompressed/theirs
                        time:   [98.560 us 98.891 us 99.318 us]
```
This is the result of my very basic change and I'll continue optimising the performance a bit more.

**Comment by gakonst** [comment]
Nice! Thank you for taking a look.

**Comment by paberr** [comment]
Ok, it seems that saving the additional copy operation actually hurt the performance.
I played around a bit with your benchmarking code and added:
- a benchmark for a single field element
- a third branch to compare to called `mix`, which is my implementation, just with the additional copy operation

Here's the result:
```
write/ours              time:   [109.25 us 109.60 us 110.06 us]
write/theirs            time:   [115.23 us 115.64 us 116.10 us]
write/mix               time:   [98.144 us 98.384 us 98.714 us]

write_uncompressed/ours time:   [75.913 us 76.064 us 76.266 us]
write_uncompressed/theirs
                        time:   [92.986 us 93.353 us 93.839 us]
write_uncompressed/mix  time:   [74.795 us 75.238 us 75.804 us]

write field/ours        time:   [38.366 us 38.665 us 39.018 us]
write field/theirs      time:   [49.276 us 49.402 us 49.563 us]
write field/mix         time:   [36.814 us 37.043 us 37.366 us]
```

I'll push the improvements to a new branch and open a PR. Thanks for pointing me to this. :)

**Comment by Pratyush** [comment]
Thanks for looking into this @paberr! I believe I can close the issue now.
