### ISSUE TITLE
128 bit scalar multiplications?

### ISSUE THREAD

**Issue by burdges** [arkworks-rs/snark#133]
Is there an exposed mechanism to do 128 bit scalar multiplications?  I know the zcash crates have this internally with their BitIterator but do not expose it.

**Comment by Pratyush** [comment]
You can do 
```rust
let num = 10u128;
let scalar = Fr::from(num);
g.mul(scalar);
```

**Comment by burdges** [comment]
Thanks!   I  saw that https://github.com/scipr-lab/zexe/blob/master/algebra-core/src/fields/mod.rs#L301 iterates over all bits of the scalar, not just the low ones, and https://github.com/scipr-lab/zexe/blob/master/algebra-core/src/curves/models/short_weierstrass_jacobian.rs#L72 calls `double_in_place` for every bit, but I'd missed that `double_in_place` shortcuts: https://github.com/scipr-lab/zexe/blob/master/algebra-core/src/curves/models/short_weierstrass_jacobian.rs#L389
