### ISSUE TITLE
Add method to prime field to get the ith root of unity

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/snark#137]
Currently `prime_field.root_of_unity()` returns a group element of order `2^{F::PARAMS::TWO_ADICITY}`. 

It would be convenient to have a method on PrimeField to get the root of unity for a given power of 2. This operation comes up fairly often, including the evaluation domain API of zexe.

It could also be extended in the future to get non-power of two roots.

**Comment by paberr** [comment]
I believe this is actually addressed in #179.

**Comment by Pratyush** [comment]
I believe @paberr is right
