### ISSUE TITLE
Parallelize Groth16

### ISSUE THREAD

**Issue by gakonst** [arkworks-rs/snark#157]
Calculating a b and c can be done in parallel here:
https://github.com/scipr-lab/zexe/blob/master/groth16/src/prover.rs#L268-L332

Should improve our proving times. Implementation via crossbeam scoped threads should be straightforward.

I'll tackle this this week

**Comment by gakonst** [comment]
Moving this comment here: https://github.com/scipr-lab/zexe/pull/159#issuecomment-605853721

I think it's not as trivial due to how the signature of the `miller_loop` function is in the trait. Rayon iterators are not really `IntoIterator`

**Comment by Pratyush** [comment]
Can this issue be closed @gakonst?
