### ISSUE TITLE
Insufficient constraints for fn inverse in Fp2 (and other) extension field gadgets

### ISSUE THREAD

**Issue by UlrichHaboeck75** [arkworks-rs/snark#172]
As explained in detail in [the same issue just patched](https://github.com/ZencashOfficial/ginger-lib/issues/45) in our Zexe fork, the two constraints used in the `fn inverse` in `r1cs-std/src/fields/fp2.rs` are not sufficient to enforce the inverse relation. The same issue is found in the following gadgets: 
- `Fp4Gadget`, 
- `FP6Gadget` in fp6_2over3.rs,  and
- `Fp12Gadget`.

The issue is easily patched, one just has to keep the equation for "real" part of the product, i.e. 1 - nonresidue * v1 = a0 * b0 in the notation of the gagdet.

**Comment by Pratyush** [comment]
Thanks for bringing this up! I've opened PR #174 with your fix (with proper credit in the code)
