### ISSUE TITLE
Unify Extension Field arithmetic

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/snark#182]
Currently we have a number of quadratic and cubic extension fields that have essentially the same arithmetic with respect to their base field. We should unify these implementations, perhaps with the following traits:

```rust
pub trait QuadraticExtensionParameters {
	/// The base field that we are building an extension over.
	type BaseField: Field;
	/// The underlying prime field.
    type Fp: PrimeField;
	/// The degree of the extension with respect to the PrimeField.
	const DEGREE_WRT_FP: usize;
	/// The non-residue used to construct the extension.
	const NONRESIDUE_FOR_TOWER: BaseField;

}

pub trait CubicExtensionParameters {
	type BaseField: Field;
    type Fp: PrimeField;
	const DEGREE_WRT_FP: usize;
	const NONRESIDUE_FOR_TOWER: BaseField;
}
```

Then, in a module like `Fp2`, we can do the following:
```rust
pub trait Fp2Parameters

**Comment by jon-chuang** [comment]
I am keen on this as I would like to jointly optimise the extension field arithmetic, which seems a major bottleneck to performance (currently aiming for 0.8-0.9ms for BLS12_381 pairing)

**Comment by paberr** [comment]
This seems like a great idea that could remove a lot of code duplication in the field arithmetic.

**Comment by Pratyush** [comment]
This was done in #233
