### ISSUE TITLE
Better error handling for field deserialization

### ISSUE THREAD

**Issue by kobigurk** [arkworks-rs/snark#184]
I believe the deserialization logic here should be improved: https://github.com/scipr-lab/zexe/blob/e1db7c5fede8ba5a0f5b3958692de44da65c1cb6/algebra-core/src/fields/macros.rs#L175

When Zexe tries to read a byte stream and it gets a value that isn’t in the field it returns 0. This is both confusing for users to check for errors and prevents from getting a valid 0 value.

A current approach to mitigate it is https://github.com/scipr-lab/zexe/pull/181/files#diff-0d3539aa74111fa4e3ea4d5b08b7278cR289, but should be improved.

**Comment by Pratyush** [comment]
I believe this is fixed now? `from_repr` returns an `Option<Self>`.
