### ISSUE TITLE
Move ff-fft into algeba-core

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/snark#185]
It is algebra after all, and will reduce the clutter.

**Comment by Pratyush** [comment]
I split it out because users that do not want to deal with FFTs do not have to. furthermore, tests in `ff-fft` depend on `algebra`, so moving `ff-fft` into `algebra-core` would cause a cyclic dependency.

**Comment by jon-chuang** [comment]
Perhaps more generic tests for fft should be reserved for `algebra-core`, while the BLS-specific test should be moved into `algebra/tests/fft.rs`?

This seems to be the standard practice. For instance for MSMs too. Although, it is true that `fft` is not elliptic curve specific. But same thing can be said of fields.

Btw, there are no benchmarks for msm/fft/polynomial algebra?

**Comment by Pratyush** [comment]
> Though, actually, I was reading #179 (files), it seems that you would like a new crate for fft-related field stuff? This does make sense to me.

I think the idea there is to make it a new trait, not a new crate.

Maybe a solution to having this problem of requiring `algebra` just for testing is to instead make a `TestField` and `TestCurve` in `algebra-core` that we use for testing. Maybe it can be a small 64-bit field? What do you think?

**Comment by jon-chuang** [comment]
I will take a look. It's true that the tests associated to algebra-core should be in the same crate, rather than in `algebra`.

**Comment by sunhuachuang** [comment]
Don't worry about test problem. If the dependency is placed under dev, there will be no circular dependency. So, move all fft tests code to `algeba-core/tests/fft.rs`. if need help, I can help achieve it.

**Comment by Pratyush** [comment]
Since this issue, we've split things up further, so now `algebra-core` doesn't exist.
