### ISSUE TITLE
Add is_equal gadget

### ISSUE THREAD

**Issue by kobigurk** [arkworks-rs/snark#190]
It's useful to have a gadget that outputs whether two numbers are equal or not, or equivalently if an element is zero (then you just check the difference). A folklore way of doing it for `x` is:

* Allocating an unconstrained variable `inv_x` that contains the inverse of `x` is `x !=0` and `0` otherwise
* Constraining `x*inv_x == 1 - result`
* Constraining `x*result == 0`

An example implementation exists here: https://github.com/celo-org/bls-zexe/pull/148/files#diff-529c1da151158d954e4e07b51e4542d1R96

**Comment by Pratyush** [comment]
So this is different from the `{ConditionalEq,Eq}/Gadget` in that it returns a variable which is 0 if they're equal and 1 otherwise? (Or vice-versa?)

**Comment by kobigurk** [comment]
Vice-versa, but yeah, exactly. It's useful in the cases you later on need to use that for some other things rather than just assert.

**Comment by Pratyush** [comment]
This is implemented in master now, under the `EqGadget` trait.
