### ISSUE TITLE
cleanup sw6 pairing and impl

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/snark#196]
It seems algebra as a crate should be reserved for parameters; to preserve consistency, I suggest that sw6 pairing related formulas, currently in algebra, be moved to algebra-core as is standard for all other curves, by someone who is more qualified.

**Comment by Pratyush** [comment]
`ark-ec` (formerly part of `algebra-core`) is really for *families* of curves; SW6 is a standalone curve. It's also been superseded by BW6, so I think it's fine to close this issue.
