### ISSUE TITLE
Consistent bit order across ToBitsGadget?

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/snark#238]
In the current library, we know that:
- FpGadget's `to_bits` is big-endian: https://github.com/scipr-lab/zexe/blob/master/r1cs-std/src/fields/fp/mod.rs#L359
- UInt8's `to_bits` is little-endian: https://github.com/scipr-lab/zexe/blob/master/r1cs-std/src/bits/mod.rs#L66

Would it be worthwhile to have a global consistency such that all `to_bits` are big-endian OR little-endian?

**Comment by Pratyush** [comment]
Yeah, it's been on my stack as I've been going through the refactor. Maybe a good idea would be to have `to_bits_le` and `to_bits_be`, and define one of them in terms of the other

**Comment by Pratyush** [comment]
Fixed, by moving things to `to_bits_le`
