### ISSUE TITLE
Optimizing time to run example "application" code

### ISSUE THREAD

**Issue by savil** [arkworks-rs/snark#27]
Context: 
I'm trying to write example code implementing the Applications from the Zexe paper, starting with the MintOrConservePredicate.

Problem:
To get started, i copied the integration test in `dpc/tests/plain_dpc.rs`, and began modifying it to run a basic MintOrConservePredicate. However, the code-debug cycle here is very slow. The build times for dpc are slow (separate issue), but also running time for this test takes close to many painful minutes on my laptop. 

I added some timing code to identify the bottleneck:
```
<InstantiatedDPC as DPCScheme<MerkleTreeIdealLedger>>::setup: 1111.4s
InstantiatedDPC::execute: 642.0s
InstantiatedDPC::verify: 3.9s
```

i.e. generating the `PublicParameters` from the "trusted setup" is the biggest bottleneck. 

Possible fixes:
Option 1: implement `serde` for `PublicParameters`. This way i could save these parameters to a file, and load them up (not suitable for an integration test, but for a function i can put in `examples/` folder), and then do InstantiantiatedDPC::execute and ::verify as before. 

If you'd prefer not adding `serde` as an external dependency, then it could be marked as `dev-dependency` or an optional compilation feature?

I started down this rabbit hole, and it meant sprinkling serde implementation onto many many structs. So, thought i'd first check if this path is desirable.

Option 2: 
profiling the "setup" function to understand which functions are slow in it, and possibly optimising them. Haven't done this yet.

Any other options?

**Comment by Pratyush** [comment]
Hi Savil,

We're aware of our extremely slow compile times; it seems that the fastest way to iterate on changes is by compiling in release mode.

**Comment by savil** [comment]
@Pratyush thanks, yeah aside from the compile time, in the issue details above i was also trying to figure out how to reduce the running time when iterating on an example-predicate code. One idea was to save the public-parameters to disk (e.g. via `serde`), instead of generating them every time. Any opinions on the desirability of implementing that?

**Comment by savil** [comment]
let me close this to reduce noise in the issues list.
