### ISSUE TITLE
Use macros to define finite fields of different sizes

### ISSUE THREAD

**Issue by HarryR** [arkworks-rs/snark#31]
I used the following code to generate the inner loop bits for different fields:

https://gist.github.com/HarryR/84ee15617c8a47b09cde28a0c1299a4f

I don't know how well this translates to Rust, but I assume we could use macros to define the different fields (in the same vein as ctbignum), rather than copy-pasta code?

I found having to copy-pasta code to define a new field of a different size (512 bits), then modifying it, was a massive PITA.

**Comment by Pratyush** [comment]
I thought about doing this in the past, and the problem is that Rust's `macro_rules` macros can't generate code via for loops. That's why `ff_derive` uses a `proc_macro`. It could be worthwhile to try and port the `ff_derive` macro to work with `algebra` though.

**Comment by gakonst** [comment]
Should this be closed? @Pratyush

**Comment by Pratyush** [comment]
Yes, thanks!
