### ISSUE TITLE
Inquiry: Use of Rc<RefCell> over Arc<Mutex> in constraint_system.rs

### ISSUE THREAD

**Issue by saurabhchalke** [arkworks-rs/snark#375]
Hello Arkworks Team,

I have been exploring the [constraint_system.rs](https://github.com/arkworks-rs/snark/blob/master/relations/src/r1cs/constraint_system.rs) file in the snark package and I'm intrigued by a specific implementation detail concerning the choice of `Rc<RefCell>` for managing shared state.

In particular, I am referring to the following code snippet:

```rust
/// A shared reference to a constraint system that can be stored in high level variables.
#[derive(Debug, Clone)]
pub enum ConstraintSystemRef<F: Field> {
    ...
    CS(Rc<RefCell<ConstraintSystem<F>>>),
    ...
}
```

I am curious about the choice of Rc<RefCell> for ConstraintSystemRef.

Could you provide some insights into why the choice was made to use Rc<RefCell> instead of a thread-safe alternative like Arc<Mutex>? I am particularly interested in understanding the design considerations, such as the intended usage scenarios, performance aspects, or any other reasons that guided this decision.

Thank you for your time and assistance. I am looking forward to your insights on this matter.

**Comment by burdges** [comment]
Afaik we only use `ConstraintSystemRef` during circut generation, witness computation, etc.  These phases should be much faster than your actual prover, so either they're already fast single threaded, or else your circut is too big to prove.  Arkworks already uses multi-threading inside heavy curve operations, like miller loops and multi-scalar multiplications. 

I'd expect "much faster" means roughly "1 million times faster" for a somewhat general circuts, including "zk roll ups", although special purpose code could perform much better.

**Comment by saurabhchalke** [comment]
Thanks for the clarification on the use of Rc<RefCell> in Arkworks @burdges. Your insights about the performance aspects and application context were really helpful.

I'm closing this issue as my query has been adequately addressed.

**Comment by saurabhchalke** [comment]
@burdges I did end up creating an async version of the constraint_system for my use case.
[Sharing the code for reference](https://github.com/zkHubHQ/snark/blob/distributed-groth16/relations/src/r1cs/constraint_system_async.rs).

Do you think you'd like this upstreamed into the main repo?

**Comment by burdges** [comment]
Ain't my decission.  A priori, I'd expect this always winds up being a pessimisation, albeit only a small pessimisation, so why?

We anyways need `ConstraintSystemRef` to work with [`alloc::sync`](https://doc.rust-lang.org/alloc/sync/index.html) not `std::sync`, so you cannot use `std::sync::Mutex`, and `tokio::sync::Mutex` uses `std::sync::Mutex`.  

Almost everyone wants verifiers that run in restricted enviroments like a blockchain.  It's already a snark too of course.  Arkworks has safe multi-threading in curves, but if too exposed then multi-threading risks non-determinism which breaks concensus or invaldates your trusted setup.  Anyways `ConstraintSystemRef: Sync` sounds risky.

It's plausible different runtime checks besides `Rc` or `Mutex` make more sense here, but exactly what looks subtle.  I suppose even qcell or singleton-cell look interesting, maybe another ghost-cell decendent cell-family or frankencell somehow.

**Comment by burdges** [comment]
I suppose a constraint system built across multiple threads could let each thread to handle its own wires, after which some join operation merges them deterministically.  In principle, this would close out all `ConstraintSystemRef`s, return to the parent thread the inner `ConstraintSystem` and indexing information for the few input and output wires, and then the parent thread merges the `ConstraintSystem` types and returns new `ConstraintSystemRef`s.
