### ISSUE TITLE
Polynomial ring over a finite field

### ISSUE THREAD

**Issue by Fiono11** [arkworks-rs/snark#39]
Hello!

I would like to construct a polynomial ring over a finite field, but I am new to Rust and this type of math.
Can this library be used for this and, if so, can someone point me in the right direction?

Thanks!

**Comment by Pratyush** [comment]
Yes, it should be possible to construct F[x] for some arbitrary finite field. We already have types to represent polynomials here: https://github.com/scipr-lab/zexe/tree/master/ff-fft/src/polynomial

**Comment by Fiono11** [comment]
Thanks!
