### ISSUE TITLE
A proof of proof

### ISSUE THREAD

**Issue by amakerofbonnetsandhoods** [arkworks-rs/snark#4]
Hi all,
How one can use zexe to create a circuit that verifies a GM17 proof?
Thanks,

**Comment by Pratyush** [comment]
Yes, you can find here the corresponding gadget: https://github.com/scipr-lab/zexe/blob/b37772ddf88e3f930e818a6523e3c5ccc813cfdc/dpc/src/gadgets/verifier/gm17.rs
