### ISSUE TITLE
Issue when importing external dependency

### ISSUE THREAD

**Issue by Fiono11** [arkworks-rs/snark#40]
When I add:

[dependencies]
ff-fft = { git = "https://github.com/scipr-lab/zexe/" }

I get the error:

error: failed to load source for a dependency on `ff-fft`

Caused by:
  Unable to update https://github.com/scipr/zexe

Caused by:
  failed to clone into: /home/fiono/.cargo/git/db/zexe-3255c1405822b681

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

Caused by:
  failed to acquire username/password from local configuration

Any idea why?

**Comment by Pratyush** [comment]
Hmm seems like an issue with your got config? This repo is public so you shouldn't need to log in for anything...

Maybe try running `cargo update`?

**Comment by Fiono11** [comment]
Worked! Thanks :)
