### ISSUE TITLE
Polynomial coefficient as ScalarField

### ISSUE THREAD

**Issue by Fiono11** [arkworks-rs/snark#48]
Hello! I am trying to use a polynomial coefficient as a ScalarField of an elliptic curve, like in the following function: 

```rust
pub fn coeff_committment<G: ProjectiveCurve, F: PrimeField>(p: DensePolynomial<F>, g: G) -> Vec<G> {
    let mut points = Vec::new(); 
    for i in 0..p.coeffs.len() {
        let point = g.mul_assign(p.coeffs[i]);
        points.push(g);
    }
    points
}
```
But I am getting the following error: "the trait std::convert::From<F> is not implemented for <<G as algebra::curves::ProjectiveCurve>::ScalarField as algebra::fields::PrimeField>::BigInt". 

Can someone help me, please? Thanks!

**Comment by Pratyush** [comment]
Hi!

You can do it as follows:

```rust
pub fn coeff_committment<G: ProjectiveCurve>(p: DensePolynomial<G::ScalarField>, g: G) -> Vec<G> {
	p.coeffs.iter().map(|c| g.mul(c.into_repr())).collect()
    
}
```

**Comment by Fiono11** [comment]
Almost there, but it stills gives me this error: 

"expected type `&<G as algebra::curves::ProjectiveCurve>::ScalarField`
              found type `<<G as algebra::curves::ProjectiveCurve>::ScalarField as algebra::fields::PrimeField>::BigInt`

consider constraining the associated type `<<G as algebra::curves::ProjectiveCurve>::ScalarField as algebra::fields::PrimeField>::BigInt` to `&<G as algebra::curves::ProjectiveCurve>::ScalarField`"

**Comment by Fiono11** [comment]
There is no need to convert to BigInt, it works now. Thank you so much!

**Comment by Pratyush** [comment]
I realise my code snippet is a bit different from what you originally posted. My snippet produces `[g^a_0, g^a_1, ..., g^a_d]`, whereas yours produces `[g^a_0, g^{a_0 + a_1}, ..., g^{a_0, + ... + a_d}]`.
