### ISSUE TITLE
Failing test for Boolean

### ISSUE THREAD

**Issue by kobigurk** [arkworks-rs/snark#5]
It seems that there are missing asserts in this line and the next: https://github.com/scipr-lab/zexe/blob/14445938364f7ee97f42dfe7eaa1393f1f0b87c1/snark-gadgets/src/bits/boolean.rs#L1797, which causes test compilation to fail.

Does this change make sense?
```
-            Boolean::enforce_nand(&mut cs, &[Boolean::constant(false)]).is_ok();
-            Boolean::enforce_nand(&mut cs, &[Boolean::constant(true)]).is_err();
+            assert!(Boolean::enforce_nand(&mut cs, &[Boolean::constant(false)]).is_ok());
+            assert!(Boolean::enforce_nand(&mut cs, &[Boolean::constant(true)]).is_err());
```

**Comment by Pratyush** [comment]
Thanks, I believe https://github.com/scipr-lab/zexe/pull/15 should fix this?

**Comment by kobigurk** [comment]
Yep, that's great! Thanks!
