### ISSUE TITLE
DenseOrSparsePolynomial division out of bounds

### ISSUE THREAD

**Issue by CPerezz** [arkworks-rs/snark#68]
I've this function which compiles perfectly:
It basically creates a numerator polynomial which is always the same and then an iterator of denominators.
Then iterates over them dividing the numerator by the denominators returning the results unwrapped.

```rust
pub fn compute_to_n_lagrange_polys(&self, size: usize) -> Vec<Polynomial<E::Fr>> {
        use ff_fft::{DenseOrSparsePolynomial, SparsePolynomial};
        use std::convert::TryInto;
        use std::str::FromStr;
        // Compute the denominator.
        // TODO: What should we do with the constant `Cx`?
        let numerator: DenseOrSparsePolynomial<E::Fr> =
            SparsePolynomial::from_coefficients_slice(&[
                (0, -E::Fr::one()),
                (size + 1, E::Fr::one()),
            ])
            .into();

        let denominators: Vec<DenseOrSparsePolynomial<E::Fr>> = {
            let mut den: Vec<DenseOrSparsePolynomial<E::Fr>> = Vec::default();
            for i in 0..=size {
                den.push(
                    SparsePolynomial::from_coefficients_slice(&[
                        (1, E::Fr::one()),
                        // Weird but `from_repr` and `from` are not suitable for this impl.
                        (0, -E::Fr::from_str(&format!("{}", i)).ok().unwrap()),
                    ])
                    .into(),
                );
            }
            den
        };

        let res: Vec<Polynomial<E::Fr>> = denominators
            .into_iter()
            .map(|den| numerator.divide_with_q_and_r(&den).unwrap().0)
            .collect();
        res
    }
```

When I call it with the input `size = 1`, it runs perfectly and provides the correct resulting polynomial.

The problem is that for `size > 1`  this is what happens:
```
panicked at 'index out of bounds: the len is 4 but the index is 4', ~/.cargo/git/checkouts/zexe-f74c42809fa6cfe1/859430c/ff-fft/src/polynomial/mod.rs:124:21
```

Maybe I'm doing something wrong since for `size = 1` it works, but it should divide the numerator for each denominator of the iterator.

**Comment by Pratyush** [comment]
I think it's because of the inverted order of the coefficients when constructing denominators. The following code works (I took the liberty of making some changes to make it more idiomatic):
```rust
    fn compute_to_n_lagrange_polys(&self, size: usize) -> Vec<Polynomial<E::Fr>> {
        use crate::{DenseOrSparsePolynomial, SparsePolynomial};
        // Compute the denominator.
        // TODO: What should we do with the constant `Cx`?
        let numerator: DenseOrSparsePolynomial<E::Fr> =
            SparsePolynomial::from_coefficients_slice(&[
                (0, -E::Fr::one()),
                (size + 1, E::Fr::one()),
            ])
            .into();

        let denominators: Vec<DenseOrSparsePolynomial<E::Fr>> = (0..=size).map(|i| {
                SparsePolynomial::from_coefficients_slice(&[
					// You don't have to use FromStr, just have to cast usize to u64.
                    (0, -Fr::from(i as u64)),
                    (1, Fr::one()),
                ]).into()
            }).collect();

         denominators
            .into_iter()
            .map(|den| numerator.divide_with_q_and_r(&den).unwrap().0)
            .collect()
    }
```

I'll add some checks to sort sparse polynomials to ensure that the slice is always sorted by order of coefficients.

**Comment by CPerezz** [comment]
> I think it's because of the inverted order of the coefficients when constructing denominators. The following code works (I took the liberty of making some changes to make it more idiomatic):
> 
> ```rust
>     fn compute_to_n_lagrange_polys(&self, size: usize) -> Vec<Polynomial<E::Fr>> {
>         use crate::{DenseOrSparsePolynomial, SparsePolynomial};
>         // Compute the denominator.
>         // TODO: What should we do with the constant `Cx`?
>         let numerator: DenseOrSparsePolynomial<E::Fr> =
>             SparsePolynomial::from_coefficients_slice(&[
>                 (0, -E::Fr::one()),
>                 (size + 1, E::Fr::one()),
>             ])
>             .into();
> 
>         let denominators: Vec<DenseOrSparsePolynomial<E::Fr>> = (0..=size).map(|i| {
>                 SparsePolynomial::from_coefficients_slice(&[
> 					// You don't have to use FromStr, just have to cast usize to u64.
>                     (0, -Fr::from(i as u64)),
>                     (1, Fr::one()),
>                 ]).into()
>             }).collect();
> 
>          denominators
>             .into_iter()
>             .map(|den| numerator.divide_with_q_and_r(&den).unwrap().0)
>             .collect()
>     }
> ```
> 
> I'll add some checks to sort sparse polynomials to ensure that the slice is always sorted by order of coefficients.

I see, didn't thought that the order will mater if what you are building is a SparsePolynomial (you already set the degree of each monomial).


Also, I tried to use `-Fr::from(i as u64))` and it does not compile since `From` is expecting an `u8`. And it's weird since I saw that `From` trait was implemented for all of the basic unsigned integer types, but for some reason it just does not compile (or I'm missing some dependency).

**Comment by Pratyush** [comment]
This issue should be fixed in master now.

Re: your issue with `From`, sometimes type inference can be finicky, so you might want to do something like `<From<u64>>::from(i as u64)`, or some variant thereof.

**Comment by CPerezz** [comment]
I see.

Thanks a lot for your help!
