### ISSUE TITLE
natural logarithm in variable_base.rs

### ISSUE THREAD

**Issue by debris** [arkworks-rs/snark#79]
I'm trying to make zexe work with parity's [`substrate`](https://github.com/paritytech/substrate) runtime. In order to achieve that, I need to make zexe work with `no_std` and also remove all floating point operations. While doing the later, I stumbled upon an interesting line in `variable_base.rs`.

https://github.com/scipr-lab/zexe/blob/6c5ea20bc44f2a1edb1fd281d768ab57b0caa78f/algebra/src/msm/variable_base.rs#L14-L18

Line `17` looks very similar to `ceil(ln(scalars_len))` and when I look at the commit history, this is exactly what it used to be:

https://github.com/scipr-lab/zexe/blob/bf21fd2834168e74cb2b0d4a850d76cd9ef01693/algebra/src/msm/variable_base.rs#L15-L19

Since `+ 2.0` looks quite suspicious to me, I compared the two implementations and it appears that it is not what it `ceil(ln(scalar_len))` used to be. I don't understand how the result of this equation affects the code further, but if it can be only approximately `ceil(ln(scalar_len))` maybe it is possible to replace it with the implementation that doesn't use floats?

Here is the link to the rust playground with 3 different implementation of this line:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=845f4ca1f1641eaf50445413f97569eb

**Comment by kobigurk** [comment]
In my understanding, this is a value that empirically just gives better
results. It doesn't affect the result of the computation. This value is in
line with what I know from libff.

**Comment by Pratyush** [comment]
@kobigurk is exactly right, it’s a value that I picked up from libsnark while trying to optimize the MSM code

**Comment by debris** [comment]
@kobigurk @Pratyush  Thank you for clarifying this so fast 🙌
