### ISSUE TITLE
Possible optimizations for GM17 proof verification gadget

### ISSUE THREAD

**Issue by sanchopansa** [arkworks-rs/snark#8]
Hi, @Pratyush!

I've been looking into the implementation of the SNARK gadget for proof verification of GM17 proofs. I noticed a couple of things regarding potential optimizations that we also discussed with @arielgabizon and I'm curious to hear your thoughts on those:

- if I'm not mistaken, the `g_psi` computed [here](https://github.com/scipr-lab/zexe/blob/master/dpc/src/gadgets/verifier/gm17.rs#L133) is a linear combination of the verification key and the public inputs to the SNARK, thus it requires one scalar multiplication and one addition per public input, so is quite expensive to compute inside the SNARK. Is there any particular reason why this is currently being computed in the circuit (the alternative being to provide `g_psi` as a public input and have the verifier check that it has been computed correctly)?
- in the multi-Miller loop [here](https://github.com/scipr-lab/zexe/blob/master/dpc/src/gadgets/verifier/gm17.rs#L164) the pairing `e(pvk.g_alpha_pc.clone(), pvk.h_beta_pc.clone())` consists only of elements of the verification key (so only of public inputs), so it should also be possible to compute it outside of the circuit and provide it as a public input to the gadget
- if `g_psi` is computed outside of the circuit as suggested above, I think the pairing `e(g_psi_prep, pvk.h_gamma_pc.clone())` can also be computed outside and provided as a public input.

Overall, the above could potentially lead to quite a few constraints being removed from the verification gadget (at a small additional cost for the verifier), unless I'm missing something.

What are your thoughts on the above?

**Comment by Pratyush** [comment]
Ah, Zexe requires hiding the verification key, and that's why all those things are computed inside the circuit. If your application doesn't require that, then  all the above optimisations should apply!

**Comment by sanchopansa** [comment]
I see, thanks for the clarification! Ariel had a suspicion that this might be the case... Indeed for our use case, the verification key is public, so we could shave off some constraints.

**Comment by arielgabizon** [comment]
It doesn't contradict though, that having as a gadget a GM/G16 verifier where the PI is outside is useful (Maybe our work can end up adding such a gadget to ZEXE)

**Comment by sanchopansa** [comment]
Totally. I think this is definitely something we could contribute, if it's of interest. (cc @stefandeml)

**Comment by arielgabizon** [comment]
Actually this might be a good opportunity to mention @ebfull's observation from a while back, that in fact different circuits could use verification keys with same alpha, beta   and just a different delta. So at least if you're willing to bound in advance the size of the circuits, you could save the e(alpha,beta) computation in ZEXE (don't know if it's worth the effort)
