### ISSUE TITLE
Allow `/` in constraint namespace

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/snark#83]
Currently the test constraint system does not allow `/` to be used in names for constraints. However, I would like to use `/` for describing certain computations, e.g. `c = a / b`. 

Could the separator be changed, or perhaps allow for slashes in the name?

**Comment by Pratyush** [comment]
Do you have a suggestion for a new separator? (Maybe a Unicode character?)

**Comment by ValarDragon** [comment]
If you want to stick to ascii, then I'd suggest `->`, or `::`.

If unicode is fine, then perhaps `∕` (The division slash https://www.fileformat.info/info/unicode/char/2215/index.htm), or § (https://en.wikipedia.org/wiki/Section_sign)

**Comment by Pratyush** [comment]
Hm we use `::` to namespace things in some other code, so that's a no go.

Maybe you should use `⁄` to represent division =P

(as an aside, my monospace font doesn't render  ⁄ , but does render [`╱`](https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block)))

**Comment by ValarDragon** [comment]
Ok, I'll do that for now, Thanks
