### ISSUE TITLE
[Question] Short Weirstrass curve with 381 bits subgroup

### ISSUE THREAD

**Issue by brunoffranca** [arkworks-rs/snark#84]
If I understand correctly the SW6 curve in this library has a prime order subgroup of 377 bits (for use with the BLS12-377 curve). Do you know a corresponding curve with prime order subgroup of 381 bits, so that I can use it with the BLS12-381 curve?

**Comment by Pratyush** [comment]
Do you intend to create SNARKs over this new curve? This would be inefficient because FFTs would be slow over the scalar field of the curve, because the BLS12-381 base field doesn’t have enough roots of unity.

For more details, see the Zexe paper that’s linked in the README

**Comment by brunoffranca** [comment]
Thanks, I hadn't thought about it. What I want to do is to create a SNARK that proves some statements about BLS signatures. Since I was already doing the BLS signatures in the BLS12-381 curve I thought it would be simpler to just use a different SW curve. But I guess it makes more sense to do the BLS signatures in the BLS12-377 curve and then I can use your SW6 curve to do the SNARKs.

P.S. I read the ZEXE paper, I just wasn't aware that the BLS12-381 root of unity was that much lower than the BLS12-377.

**Comment by Pratyush** [comment]
> P.S. I read the ZEXE paper, I just wasn't aware that the BLS12-381 root of unity was that much lower than the BLS12-377.

Sorry, didn't mean to imply you hadn't done your homework! That point is kinda buried in the technical sections, and easy to miss, so just wanted to point it out =)

**Comment by brunoffranca** [comment]
Oh, don't worry. I didn't take it the wrong way. :)
