### ISSUE TITLE
[Question] Using MPC for parameter generation.

### ISSUE THREAD

**Issue by brunoffranca** [arkworks-rs/snark#89]
Are there plans to support distributed parameter generation? Or could I maybe modify the Powers of Tau library (https://github.com/ebfull/powersoftau) to generate parameters for the SW6 curve?

**Comment by Pratyush** [comment]
Hmm currently we don’t have an implementation of the powers of Tau, but it should (hopefully) be a mechanical change to translate @ebfull’s repo to use Zexe instead. I know that @kobigurk was also interested in this.

**Comment by kobigurk** [comment]
My desire is to adapt https://github.com/kobigurk/phase2-bn254/ to the Zexe curves.
It's originally based on Zcash's repo, which then Matter Labs took and added support for larger parameters by working in chunks. We use it for https://github.com/weijiekoh/perpetualpowersoftau, where we generate parameters for 2^28 constraints on BN254.

Our specific repo adds a workflow for doing phase2 (which was quite manual before) and support for interoperability with circom, so we can get out-of-the-box circom circuit on Zexe curves, which is a side benefit. The main benefit is of course the MPC for the Zexe curves.

@brunoffranca if you want to help out, that would be awesome, we didn't get to tackling it yet.

**Comment by brunoffranca** [comment]
@kobigurk actually we might be able to help each other. We at Nimiq are also interested in adapting the powers of tau protocol to the ZEXE curves. And your perpetual powers of tau repo also has a lot of functionality that it's useful to us. Can I email you so that we can talk more at length?

**Comment by kobigurk** [comment]
> @kobigurk actually we might be able to help each other. We at Nimiq are also interested in adapting the powers of tau protocol to the ZEXE curves. And your perpetual powers of tau repo also has a lot of functionality that it's useful to us. Can I email you so that we can talk more at length?

Sure, feel free to reach out at kobigurk@gmail.com :)
