### ISSUE TITLE
[Question] Adding EC points and the point-at-infinity.

### ISSUE THREAD

**Issue by brunoffranca** [arkworks-rs/snark#97]
I see that, in the r1cs-std crate, the add method (https://github.com/scipr-lab/zexe/blob/master/r1cs-std/src/groups/curves/short_weierstrass/mod.rs#L131) for elliptic curves has the comment: "Incomplete addition: neither `self` nor `other` can be the neutral element". Is there then a way of doing addition when one of the points is the point-at-infinity?

**Comment by Pratyush** [comment]
One can implement a "AddorNoop" method that checks if the element is the point at infinity, and does a noop in that case, or adds the elements if not. You'd probably need to implement it via a ConditionalSelect

**Comment by brunoffranca** [comment]
Ok, thanks. That's actually not too different from what we were doing. Also, we need to include some constant FpGadgets and G2Gadgets in our circuit. For the FpGadgets we have been doing the trick of using the add_constant method on Fp::zero, and also planned to do the same with the G2Gadget. Is there a better way of introducing these constants in our circuit?

**Comment by Pratyush** [comment]
That's the best way at the moment. In the future I do plan on refactoring that infrastructure to unify addition between constants and gadgets, but haven't had time yet.
